[package]
name = "day_6"
version = "0.0.0"
authors = ["Zachary Thomas <zdcthomas@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]